"""Backward-compatible re-exports.

Security helpers and singletons now live in :mod:`routes.state`.  This module
re-exports them so existing imports (`from routes.deps import ...`) keep working.
"""

from modules.audit import clear_audit, get_recent_audit, log_action
from routes.state import (
    ALLOWED_SYSTEM_COMMANDS,
    ENV_FILE_PATH,
    SESSION_TOKEN,
    SESSION_TOKEN_PATH,
    _mask_secret,
    _normalize_filename,
    _parse_document_command,
    _write_env_keys,
    calendar,
    documents,
    handle_user_input,
    llm,
    mail,
    memory_manager,
    notes,
    pending_documents_actions,
    process_command,
    require_document_confirmation,
    require_session_token,
    skill_registry,
    stt,
    system_actions,
    tts,
    validate_system_command,
    validate_ws_token,
    vault,
    vision,
    web_browse,
)

__all__ = [
    "SESSION_TOKEN",
    "SESSION_TOKEN_PATH",
    "ALLOWED_SYSTEM_COMMANDS",
    "require_session_token",
    "validate_system_command",
    "validate_ws_token",
    "memory_manager",
    "system_actions",
    "calendar",
    "mail",
    "notes",
    "web_browse",
    "llm",
    "tts",
    "documents",
    "stt",
    "skill_registry",
    "pending_documents_actions",
    "ENV_FILE_PATH",
    "process_command",
    "handle_user_input",
    "_mask_secret",
    "_write_env_keys",
    "_normalize_filename",
    "_parse_document_command",
    "require_document_confirmation",
    "vision",
    "vault",
    "log_action",
    "get_recent_audit",
    "clear_audit",
]
